import { Inter } from 'next/font/google'
import './globals.css'
import Sidebar from '@/components/Sidebar'
import News from '@/components/News'
import Navbar from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'infootball',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main className="px-2 md:px-16 md:py-2 text-textPrimary h-[100vh] overflow-y-scroll scrollbar-hide">
          <Navbar />
          <section className="flex space-x-4 justify-center items-start">
            <Sidebar />
            {children}
            <News />
          </section>
        </main>
      </body>
    </html>
  )
}
